export enum SemanticIssueType {
  DUPLICATED_ID = "DUPLICATED_ID",
  NON_EXISTING_PROPERTY_REFERENCED = "NON_EXISTING_PROPERTY_REFERENCED",
  NON_EXISTING_SEGMENT_REFERENCED = "NON_EXISTING_SEGMENT_REFERENCED",
  DUPLICATED_FEATURE_FLAG_NAME = "DUPLICATED_FEATURE_FLAG_NAME",
  ROLLOUT_PERCENTAGE_SUM_NOT_ONE_HUNDRED = "ROLLOUT_PERCENTAGE_SUM_NOT_ONE_HUNDRED",
  DUPLICATED_PROPERTY_PATH = "DUPLICATED_PROPERTY_PATH",
  PART_OF_CYCLIC_DEPENDENCY = "PART_OF_CYCLIC_DEPENDENCY",
  CYCLIC_DEPENDENCIES_PRESENT = "CYCLIC_DEPENDENCIES_PRESENT",
  CONDITION_PROPERTY_DATA_TYPE_MISMATCH = "CONDITION_PROPERTY_DATA_TYPE_MISMATCH",
  NO_VALUES_ON_MATCH = "NO_VALUES_ON_MATCH",
}
